version: '2.1'
services:

  app:
    image: wyveo/nginx-php-fpm
    container_name: chat-app
    restart: always
    volumes:
        - .:/home/www/app
        - ~/.composer:/root/.composer
        - ./docker/root/nginx/host.d:/etc/nginx/conf.d
    ports:
      - 0.0.0.0:7000:80/tcp
    networks:
      - chat

  db:
    image: mysql:5.7
    hostname: chat-db
    container_name: chat-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: chat
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    labels:
      SERVICE_NAME: chat-db
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=secret --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 3s
      retries: 10
    networks:
      - chat
    volumes:
      - ./.data/mysql:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: chat-redis
    labels:
      SERVICE_NAME: chat-redis
    networks:
      - chat

networks:
  chat:
    driver: bridge
